baseURL = "https://umairsaeed.com/"
title = "Umair's Blog"
languageCode = "en-US"

# Theme to use
theme = "talespin"

pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "monokai"

paginate = 10
preserveTaxonomyNames = true

[author]
  name = "Umair Saeed"

[taxonomies]
  category = "categories"
  tags = "tags"

[permalinks]
  posts = "/:filename"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3


# `BlackFriday` is Hugo's built-in markdown rendering engine.
[blackfriday]
  extensions = ["hardLineBreak"]
  fractions = false
  plainIDAnchors = true


[params]
  # Determines which sections are used to build the home screen.
  mainSections = ["posts"]
  googleAnalyticsId = "G-8V6E04YTKR"

[params.social]
  [[params.social.networks]]
    identifer = "twitter"
    url = "https://twitter.com/umairsd"

  [[params.social.networks]]
    identifer = "github"
    url = "https://github.com/umairsd"

  [[params.social.networks]]
    identifer = "linkedin"
    url = "https://www.linkedin.com/in/umairsd/"

  [[params.social.networks]]
    identifer = "goodreads"
    url = "https://www.goodreads.com/umairsd"

  [[params.social.networks]]
    identifer = "instagram"
    url = "https://www.instagram.com/umairsd/"


[services.rss]
    limit = 30

# Add support for Atom feed.
[mediaTypes]
    [mediaTypes."application/atom"]
    suffixes = ["xml"]

[outputFormats.Atom]
    mediaType = "application/atom"
    baseName = "index"
    isPlainText = false

[outputs]
    home = [ "HTML", "Atom" ]